---
title: "Making of a Sole Survivor"
author: "Uygar Sozer"
date: "3/22/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=FALSE, echo = TRUE)
```

# Motivation

As I was winding down after the finals week watching *Survivor: Africa*, which marks the 22nd season I have seen of the reality TV competition series Survivor, I was once again theorizing about who among the cast was going to make it to the top this time around. As a fan of this show, I get very invested in trying to figure out the logic that underlies the personal relationships and strategic moves in the game, all for the sole purpose of making it to the end and getting a shot at winning the $1 million cash prize.

The reason why I love this show so much is that the game environment exposes so much about our psyche, and as with anything involving human psychology, what happens in the game is always so unpredictable. My personal goal embarking on this project was to try to estimate what kind of factors contribute to what level when the game comes to a close and a winner is announced.

# I. *Survivor US*

Survivor is a popular show and it's easy to understand why. The rules of the game are very simple, it's a proven formula, and it keeps the fans of the show coming back for more. As with any other TV series finishing up their 40th season, there are only a handful aspects of the game that show producers haven't tried to tinker with over the course of the last 20 years to keep things fresh. But the base rules are the same.

16 to 20 castaways are placed in a remote location and divided up into tribes. The goal? Making it to the end of the 39 days of the game without getting voted off, whether that is through winning immunity challenges to keep you safe from votes, or making alliances to vote with, not against, you. At the end of the 39 days, only 3 (or 2) survivors stand to make their case to the jury as to why they should claim the title of sole survivor and the $1 million prize. This is where it gets interesting. The jury is 7-10 castaways that were most recently voted out of the tribe. So your job as a finalist now is to convince the people you had a hand in voting out why they should write you in as their winner.

The general consensus among the fans as well as the previous castaways is that there is always a great deal of luck involved in deciding who makes it to the end. So in this project I decided to solely focus on the finalists of the game, the two or three survivors standing at the end with different (or similar) styles of game play for each other. When the power shifts to the jury, what are the qualities of a finalist that helps or hinders them in their pursuit of winning the game? Can I somehow quantify aspects of how these finalists played the game that would allow me to compare them to each other, regardless of what season they come from?

# II. Descriptive statistics, feature engineering

Data was obtained from ```survivoR``` package in R, available at the public Github repo [_doehm/survivoR_](https://github.com/doehm/survivoR).




# III. Modeling

# IV. Bootstrap estimates

# V. Clustering

# Conclusions